<!DOCTYPE TS>
<TS>
  <context>
    <name>slaeconv</name>
    <message>
    <source>700000/PLC/PMC</source>
    <translation>机床急停,请检查急停按钮SB1状态！(I1/I32.0)</translation>
    </message>
    <message>
    <source>700001/PLC/PMC</source>
    <translation>QF1_导轨润滑泵电机过载！(I7/I32.6)</translation>
    </message>
    <message>
    <source>700002/PLC/PMC</source>
    <translation>QF2_液压油泵电机过载！(I9/I33.0)</translation>
    </message>
    <message>
    <source>700003/PLC/PMC</source>
    <translation>QF3_冷却泵1电机过载！(I11/I33.2)</translation>
    </message>
    <message>
    <source>700004/PLC/PMC</source>
    <translation>QF4_冷却泵2电机过载！(I12/I33.3)</translation>
    </message>
    <message>
    <source>700005/PLC/PMC</source>
    <translation>QF5_冷却泵3电机过载！(I13/I33.4)</translation>
    </message>
    <message>
    <source>700006/PLC/PMC</source>
    <translation>QF6_吸雾器电机过载！(I14/I33.5)</translation>
    </message>
    <message>
    <source>700007/PLC/PMC</source>
    <translation>QF7_水冷机电机过载！(I15/I33.6)</translation>
    </message>
    <message>
    <source>700008/PLC/PMC</source>
    <translation>QF8_电箱空调电机过载！(I17/I34.0)</translation>
    </message>
    <message>
    <source>700009/PLC/PMC</source>
    <translation>QF9_冷却油箱冷却装置过载！(I19/I34.2)</translation>
    </message>
    <message>
    <source>700010/PLC/PMC</source>
    <translation>QF10_直流电源过载！(I21/I34.4)</translation>
    </message>
    <message>
    <source>700011/PLC/PMC</source>
    <translation>QF11_控制变压器过载！(I22/I34.5)</translation>
    </message>
    <message>
    <source>700012/PLC/PMC</source>
    <translation>QF14_砂轮电机过载！(I23/I34.6)</translation>
    </message>
    <message>
    <source>700013/PLC/PMC</source>
    <translation>QF15_滚轮电机过载！(I25/I35.0)</translation>
    </message>
    <message>
    <source>700014/PLC/PMC</source>
    <translation>QF16_AR润滑泵电机过载！(I27/I35.2)</translation>
    </message>
    <message>
    <source>700015/PLC/PMC</source>
    <translation>QF17_系统驱动器电源过载！(I42/I37.1)</translation>
    </message>
    <message>
    <source>700016/PLC/PMC</source>
    <translation>ALARM1_砂轮主轴制动单元报警！(I6/I32.5)</translation>
    </message>
    <message>
    <source>700132/PLC/PMC</source>
    <translation>KP12_冷却泵1冷却水流量不足！(I68/I40.3)</translation>
    </message>
    <message>
    <source>700133/PLC/PMC</source>
    <translation>KP13_冷却泵2冷却水流量不足！(I69/I40.4)</translation>
    </message>
    <message>
    <source>700134/PLC/PMC</source>
    <translation>KP14_冷却泵3冷却水流量不足！(I70/I38.5)</translation>
    </message>
    <message>
    <source>700020/PLC/PMC</source>
    <translation>ALARM5_冷却油箱液位报警！(I20/I34.3)</translation>
    </message>
    <message>
    <source>700021/PLC/PMC</source>
    <translation>ALARM6_砂轮主轴变频器报警！(I24/I34.7)</translation>
    </message>
    <message>
    <source>700022/PLC/PMC</source>
    <translation>ALARM7_滚轮电机驱动器报警！(I26/I35.1)</translation>
    </message>
    <message>
    <source>700023/PLC/PMC</source>
    <translation>ALARM8_驱动器未准备就绪！(I28/I35.3)</translation>
    </message>
    <message>
    <source>700024/PLC/PMC</source>
    <translation>ALARM9_电源模块温度报警！(I29/I35.4)</translation>
    </message>
    <message>
    <source>700025/PLC/PMC</source>
    <translation>ALARM10_电主轴电机温度报警！(I41/I37.0)</translation>
    </message>
    <message>
    <source>700026/PLC/PMC</source>
    <translation>ALARM11_电主轴润滑泵润滑油液位报警！(I43/I37.2)</translation>
    </message>
    <message>
    <source>700027/PLC/PMC</source>
    <translation></translation>
    </message>
    <message>
    <source>700028/PLC/PMC</source>
    <translation></translation>
    </message>
    <message>
    <source>700029/PLC/PMC</source>
    <translation>KP3_主轴润滑泵气压回路气压低！(I48/I37.7)</translation>
    </message>
    <message>
    <source>700030/PLC/PMC</source>
    <translation></translation>
    </message>
    <message>
    <source>700031/PLC/PMC</source>
    <translation>异步子程序输出出错！</translation>
    </message>
    <message>
    <source>700032/PLC/PMC</source>
    <translation>机床水冷回路1有故障！(I44/I37.3)</translation>
    </message>
    <message>
    <source>700033/PLC/PMC</source>
    <translation>机床水冷回路2有故障！(I45/I37.4)</translation>
    </message>
    <message>
    <source>700034/PLC/PMC</source>
    <translation>机床水冷回路3有故障！(I46/I37.5)</translation>
    </message>
    <message>
    <source>700035/PLC/PMC</source>
    <translation>机床水冷回路4有故障！(I47/I37.6)</translation>
    </message>
    <message>
    <source>700036/PLC/PMC</source>
    <translation>机床水冷回路5有故障！(I62/I39.5)</translation>
    </message>
    <message>
    <source>700037/PLC/PMC</source>
    <translation>机床水冷回路6有故障！(I63/I39.6)</translation>
    </message>
    <message>
    <source>700038/PLC/PMC</source>
    <translation>机床水冷回路7有故障！(I64/I39.7)</translation>
    </message>
    <message>
    <source>700039/PLC/PMC</source>
    <translation>冷却油箱漏油！(I56/I38.7)</translation>
    </message>
    <message>
    <source>700040/PLC/PMC</source>
    <translation>灭火装置报警！(I57/I39.0)</translation>
    </message>
    <message>
    <source>700041/PLC/PMC</source>
    <translation>UPS装置报警！</translation>
    </message>
    <message>
    <source>700042/PLC/PMC</source>
    <translation></translation>
    </message>
    <message>
    <source>700043/PLC/PMC</source>
    <translation></translation>
    </message>
    <message>
    <source>700044/PLC/PMC</source>
    <translation></translation>
    </message>
    <message>
    <source>700045/PLC/PMC</source>
    <translation></translation>
    </message>
    <message>
    <source>700046/PLC/PMC</source>
    <translation>系统未加使能，请按“Feed enable” 键给系统加使能！</translation>
    </message>
    <message>
    <source>700047/PLC/PMC</source>
    <translation>请先在JOG方式下启动液压泵！</translation>
    </message>
    <message>
    <source>700048/PLC/PMC</source>
    <translation>手轮干涉有效,请小心操作！</translation>
    </message>
    <message>
    <source>700049/PLC/PMC</source>
    <translation>DRF有效,正在手动干预X1状态,请注意！</translation>
    </message>
    <message>
    <source>700050/PLC/PMC</source>
    <translation>DRF有效,正在手动干预X10状态,请注意！</translation>
    </message>
    <message>
    <source>700051/PLC/PMC</source>
    <translation>DRF有效,正在手动干预X100状态,请注意！</translation>
    </message>
    <message>
    <source>700052/PLC/PMC</source>
    <translation>机床X、Z轴未回零，请进行回零操做！</translation>
    </message>
    <message>
    <source>700053/PLC/PMC</source>
    <translation>机床倍率为零！</translation>
    </message>
    <message>
    <source>700054/PLC/PMC</source>
    <translation>可以切断机床总电源了(QS)！</translation>
    </message>
    <message>
    <source>700055/PLC/PMC</source>
    <translation>砂轮主轴润滑泵正在进行初次润滑，请不要开启砂轮！</translation>
    </message>
    <message>
    <source>700056/PLC/PMC</source>
    <translation>ALARM4_电箱空调报警！(I18/I34.1)</translation>
    </message>
    <message>
    <source>700057/PLC/PMC</source>
    <translation>KP1_液压油压力不足！(I10/I33.1)</translation>
    </message>
    <message>
    <source>700058/PLC/PMC</source>
    <translation>ALARM2_导轨润滑油液位报警！(I8/I32.7)</translation>
    </message>
    <message>
    <source>700059/PLC/PMC</source>
    <translation>KP2_机床气压压力太低，请检查供气回路！(I32/I35.7)</translation>
    </message>
    <message>
    <source>700060/PLC/PMC</source>
    <translation>ALARM3_冷却水液位报警！(I16/I33.7)</translation>
    </message>
	<message>
    <source>700061/PLC/PMC</source>
    <translation>防护门处于未锁定状态！</translation>
    </message>
	<message>
    <source>700062/PLC/PMC</source>
    <translation></translation>
    </message>
	<message>
    <source>700063/PLC/PMC</source>
    <translation></translation>
    </message>
  </context>
</TS>
